#!/usr/bin/python
# -*- coding: utf-8 -*-

def build_database():
    """stupid database based on: http://www.foodemissions.com/foodemissions/Calculator.aspx (by CleanMetrics)"""
    
    return {"beans":0.76,
            "lentil":0.53,
            "soybean":0.56,
            # dairy
            "butter":1.17,
            "cheese":9.81,
            "cream":0.22,
            "milk":1.02,
            "yogurt":0.9,
            # fruits, berries
            "apple":0.23,
            "appricot":0.23,
            "banana":0.27,
            "raspberry":0.57,
            "blackbarry":0.28,
            "bluebarry":0.83,
            "cherry":0.24,
            "date":0.44,
            "fig":1.54,
            "grape":0.83,
            "lemon":0.09,
            "mandarin":0.21,
            "mango":0.07,
            "melon":0.14,
            "nectarine":0.22,
            "orange":0.12,
            "peach":0.22,
            "pear":0.34,
            "pineapple":0.08,
            "plum":0.22,
            "strawberry":0.27,
            # grains
            "barley":0.23,
            "corn":0.6,
            "oat":0.31,
            "rice":2.35,
            "rye":0.25,
            "sorghum":0.28,
            "wheat":0.3,
            "mustard":1.,
            # herbs
            #"cilantro":0.2,
            #"peppermint":44.92,
            # meet, poultry
            "beef":17.59,
            "chicken":3.73,
            "egg":2.02,
            "lamb":24.09,
            "pork":5.45,
            "turkey":4.67,
            # misc
            "cocoa beans":0.57,
            "coffee beans":1.66,
            # nuts, seeds,
            "almond":1.89,
            "canola":0.85,
            #"palm":0.33,
            "pecan":1.61,
            "pistachia":1.11,
            "rapeseed":0.89,
            #"sunflower":0.88,
            "walnut":0.76,
            # oils
            "palm oil":0.44,
            "peanut oil":3.89,
            "sunflower oil":1.48,
            "soybean oil":1.48,
            # "processed food"
            "cocoa butter":1.13,
            "cocoa powder":0.3,
            "flour":0.65,
            "beer":0.38,
            "coffee":2.51,
            "ham":9.31,
            "ice cream":1.82,
            "pasta":1.24,
            "spagetti":1.24,
            "whisky":2.23,
            "margarine":1.77,
            "mashed potato":4.51,
            "wine":0.44,
            "orange juice":2.41,
            "peanut butter":1.53,
            "pepperoni":13.06,
            "pizza dough":0.72,
            "chips":3.43,
            "sausage":9.34,
            "salt":0.22,
            "soymilk":0.69,
            "sugar":3.01,
            "tofu":0.71,
            "ketchup":2.25,
            # crops
            "beet":0.11,
            "carrot":0.11,
            "onion":0.29,
            "peanut":0.57,
            # seadfood
            "cod":5.25,
            "salmon":2.88,
            "catfish":9.34,
            "herring":2.09,
            "mackerel":1.14,
            "lobster":5.37,
            "oyster":11.41,
            "shrimp":7.05,
            "tuna":3.43,
            # tubers
            "potato":0.33,
            # vegetables
            "artichoke":0.26,
            "broccoli":0.36,
            "cabbage":0.12,
            "cauliflower":0.31,
            "cucumbers":0.14,
            "garlic":0.04,
            "lettuce":0.07,
            "mushroom":0.0,
            "parsley":0.15,
            "pepper":0.26,
            "pumpkin":0.14,
            "spinach":0.34,
            "tomato":0.23,            
            }


